package com.codejava.hibernate;
// Generated 04-Jan-2021, 12:46:58 pm by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Orderdetails generated by hbm2java
 */
@Entity
@Table(name = "orderdetails", catalog = "classicmodels")
public class Orderdetails implements java.io.Serializable {

	private OrderdetailsId id;
	private int quantityOrdered;
	private double priceEach;
	private short orderLineNumber;

	public Orderdetails() {
	}

	public Orderdetails(OrderdetailsId id, int quantityOrdered, double priceEach, short orderLineNumber) {
		this.id = id;
		this.quantityOrdered = quantityOrdered;
		this.priceEach = priceEach;
		this.orderLineNumber = orderLineNumber;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "orderNumber", column = @Column(name = "orderNumber", nullable = false)),
			@AttributeOverride(name = "productCode", column = @Column(name = "productCode", nullable = false, length = 15)) })
	public OrderdetailsId getId() {
		return this.id;
	}

	public void setId(OrderdetailsId id) {
		this.id = id;
	}

	@Column(name = "quantityOrdered", nullable = false)
	public int getQuantityOrdered() {
		return this.quantityOrdered;
	}

	public void setQuantityOrdered(int quantityOrdered) {
		this.quantityOrdered = quantityOrdered;
	}

	@Column(name = "priceEach", nullable = false, precision = 22, scale = 0)
	public double getPriceEach() {
		return this.priceEach;
	}

	public void setPriceEach(double priceEach) {
		this.priceEach = priceEach;
	}

	@Column(name = "orderLineNumber", nullable = false)
	public short getOrderLineNumber() {
		return this.orderLineNumber;
	}

	public void setOrderLineNumber(short orderLineNumber) {
		this.orderLineNumber = orderLineNumber;
	}

}
